# Generated by Django 4.0.4 on 2022-11-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload')),
                ('discount_deal', models.CharField(choices=[('Hot Deals', 'Hot Deals'), ('New Arraivels', 'New Arraivels')], max_length=100)),
                ('sale', models.IntegerField(default=0)),
                ('brand_name', models.CharField(max_length=200)),
                ('discount', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
