# Generated by Django 4.0.4 on 2022-11-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload')),
                ('discount_deal', models.CharField(max_length=200)),
                ('quote', models.CharField(max_length=200)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
